[package]
name = "partition_lib"
version = "0.1.0"
edition = "2021"
description = "A crate to make the partitioning of vectors easier"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
